services:
  rabbit:
    image: rabbitmq:4.0-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: "saurabh36/configserver:v2"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root_password || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - my-db:/var/lib/mysql
    extends:
      file: common-config.yml
      service: network-deploy-service

  accounts:
    image: "saurabh36/accounts:v2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql/easy_microservice_accounts?createDatabaseIfNotExist=true"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: "saurabh36/loans:v2"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      mysql:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql/easy_microservice_loans?createDatabaseIfNotExist=true"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "saurabh36/cards:v2"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      mysql:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql/easy_microservice_cards?createDatabaseIfNotExist=true"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "bridge"
volumes:
  my-db: